"""
Django settings for smartclass project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fz7kv8db871e4cjx_jk-*mn4hbrnpf#fgcv4e2@$hpco2xuwly'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'dashboard',
]

ASGI_APPLICATION = 'smartclass.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartclass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.dashboard_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartclass.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Algiers'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ALLOWED_HOSTS = ['*', '192.168.70.25']
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Session stability defaults for local multi-app development.
# Use a unique cookie name to avoid collisions with other Django apps on 127.0.0.1.
SESSION_COOKIE_NAME = 'smartclass_sessionid'
CSRF_COOKIE_NAME = 'smartclass_csrftoken'
SESSION_COOKIE_AGE = 60 * 60 * 12  # 12 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Runtime mode: set SMARTCLASS_MODE=test|production
SMARTCLASS_MODE = os.getenv('SMARTCLASS_MODE', 'production').strip().lower()
IS_TEST_MODE = SMARTCLASS_MODE == 'test'

# Internal auto-finish scheduler runs inside Django process (no external cron required).
DASHBOARD_INTERNAL_SCHEDULER_ENABLED = True
DASHBOARD_INTERNAL_SCHEDULER_POLL_SECONDS = 20

# MQTT configuration. Default set for HiveMQ Cloud compatibility.
DASHBOARD_MQTT_ENABLED = True
DASHBOARD_MQTT_BROKER_HOST = os.getenv('DASHBOARD_MQTT_BROKER_HOST', '127.0.0.1')
DASHBOARD_MQTT_BROKER_PORT = int(os.getenv('DASHBOARD_MQTT_BROKER_PORT', '8883'))
DASHBOARD_MQTT_TOPIC = os.getenv('DASHBOARD_MQTT_TOPIC', 'smartclass/#')
DASHBOARD_MQTT_USERNAME = os.getenv('DASHBOARD_MQTT_USERNAME', '')
DASHBOARD_MQTT_PASSWORD = os.getenv('DASHBOARD_MQTT_PASSWORD', '')
DASHBOARD_MQTT_TLS_ENABLED = os.getenv('DASHBOARD_MQTT_TLS_ENABLED', 'True') == 'True'
DASHBOARD_MQTT_KEEPALIVE_SECONDS = int(os.getenv('DASHBOARD_MQTT_KEEPALIVE_SECONDS', '60'))
DASHBOARD_MQTT_RECONNECT_DELAY_SECONDS = int(os.getenv('DASHBOARD_MQTT_RECONNECT_DELAY_SECONDS', '3'))
DASHBOARD_MQTT_USERNAME = os.getenv('DASHBOARD_MQTT_USERNAME', '')
DASHBOARD_MQTT_PASSWORD = os.getenv('DASHBOARD_MQTT_PASSWORD', '')
DASHBOARD_MQTT_KEEPALIVE_SECONDS = int(os.getenv('DASHBOARD_MQTT_KEEPALIVE_SECONDS', '60'))
DASHBOARD_MQTT_RECONNECT_DELAY_SECONDS = int(os.getenv('DASHBOARD_MQTT_RECONNECT_DELAY_SECONDS', '3'))
