# Generated by Django 6.0.3 on 2026-05-11 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bike_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_alcohol_level', models.FloatField(default=0.5)),
                ('map_refresh_rate_seconds', models.PositiveIntegerField(default=5)),
                ('mqtt_broker_host', models.CharField(default='localhost', max_length=255)),
                ('mqtt_broker_port', models.PositiveIntegerField(default=1883)),
                ('mqtt_topic_helmet_status', models.CharField(default='helmet/+/status', max_length=255)),
                ('mqtt_topic_helmet_command', models.CharField(default='helmet/+/command', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('helmet_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('speed', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('alcohol_level', models.FloatField(default=0.0)),
                ('is_worn', models.BooleanField(default=False)),
                ('accel_x', models.FloatField(default=0.0)),
                ('accel_y', models.FloatField(default=0.0)),
                ('accel_z', models.FloatField(default=0.0)),
                ('gyro_x', models.FloatField(default=0.0)),
                ('gyro_y', models.FloatField(default=0.0)),
                ('gyro_z', models.FloatField(default=0.0)),
                ('battery_level', models.IntegerField(default=100)),
                ('state', models.CharField(default='Idle', max_length=20)),
                ('rider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helmet', to='dashboard.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='dashboard.rider')),
            ],
        ),
        migrations.CreateModel(
            name='GPSPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField(default=0.0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.route')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
