# Generated by Django 5.1 on 2026-03-06 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('lights_on', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False)),
                ('projector_on', models.BooleanField(default=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('danger_indicator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('PROF', 'Professor'), ('ASSISTANT', 'Assistant'), ('ADMIN', 'Administrator')], max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('rfid_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(choices=[('INFO', 'Informatique'), ('MATH', 'Mathématiques'), ('ST', 'Sciences et Techniques'), ('SM', 'Sciences de la Matière'), ('MI', 'Mathématiques et Informatique')], max_length=20)),
                ('year', models.IntegerField()),
                ('student_card_id', models.CharField(max_length=50, unique=True)),
                ('rfid_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classroom')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.staff')),
                ('students', models.ManyToManyField(blank=True, to='dashboard.student')),
            ],
        ),
    ]
