# Generated by Django 6.0.3 on 2026-05-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('CRASH', 'Crash Detected'), ('ALC', 'Alcohol Threshold Exceeded'), ('DISC', 'Disconnected during ride')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('resolved', models.BooleanField(default=False)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.helmet')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='dashboard.rider')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('technician', models.CharField(max_length=100)),
                ('battery_replaced', models.BooleanField(default=False)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='dashboard.helmet')),
            ],
        ),
    ]
