# Generated by Django 6.0.3 on 2026-05-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_incident_maintenancelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helmet',
            old_name='accel_x',
            new_name='tilt_angle',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='accel_y',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='accel_z',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='gyro_x',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='gyro_y',
        ),
        migrations.RemoveField(
            model_name='helmet',
            name='gyro_z',
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='alcohol_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='tilt_angle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='helmet',
            name='is_strapped',
            field=models.BooleanField(default=False),
        ),
    ]
