# Generated by Django 5.1 on 2026-03-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_attendance_students_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(blank=True, to='dashboard.student'),
        ),
    ]
