# Generated by Django 5.1 on 2026-03-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_attendance_student_attendance_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='presence',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
