# Generated by Django 6.0.3 on 2026-05-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_accel_x_helmet_tilt_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='platform_name',
            field=models.CharField(default='HeisenHelmet', max_length=100),
        ),
    ]
