# Generated by Django 5.1 on 2026-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_classroom_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='door',
            field=models.BooleanField(default=False),
        ),
    ]
