# Generated by Django 6.0.3 on 2026-05-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_systemsettings_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmet',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helmet',
            name='signal_strength',
            field=models.IntegerField(default=0),
        ),
    ]
