# Generated by Django 6.0.3 on 2026-05-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_helmet_latency_ms_helmet_signal_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='speed_limit',
            field=models.FloatField(default=60.0),
        ),
    ]
