# Generated by Django 5.1 on 2026-03-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_classroom_door'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='presence',
        ),
    ]
