# Generated by Django 6.0.3 on 2026-05-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_systemsettings_speed_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='mqtt_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mqtt_websocket_host',
            field=models.CharField(blank=True, default='', help_text='Public address for Web MQTT (e.g. mqtt.yourdomain.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mqtt_websocket_port',
            field=models.PositiveIntegerField(default=443, help_text='Usually 443 for WSS via Cloudflare'),
        ),
    ]
