# Generated by Django 5.1 on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_attendance_id_alter_classroom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='occupied',
        ),
    ]