# Generated by Django 5.1 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_classroom_capacity_and_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]