# Generated by Django 5.1 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_classroom_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temperature', models.FloatField(default=15.0)),
                ('max_temperature', models.FloatField(default=28.0)),
            ],
        ),
    ]
