# Generated by Django 5.1 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_temperaturesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_control_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_control_projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_manage_classrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_open_door',
            field=models.BooleanField(default=False),
        ),
    ]
