# Generated by Django 5.1 on 2026-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_session_attendance_session_attendancereport_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='dashboard.student'),
        ),
    ]
