# Generated by Django 5.1 on 2026-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_session_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='cron_interval_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_auto_finish_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
