# Generated by Django 5.1 on 2026-05-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_session_types_and_attendance_tracking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentsessionattendance',
            name='unique_session_student_attendance',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ramadan_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ramadan_start_time',
            field=models.TimeField(default='08:30:00'),
        ),
        migrations.AlterField(
            model_name='studentsessionattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsessionattendance',
            unique_together={('session', 'student')},
        ),
    ]
