# Generated by Django 5.1 on 2026-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_studentsessionattendance_unique_session_student_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mqtt_transport',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('tcp', 'TCP'), ('websockets', 'WebSockets')], default='auto', max_length=16),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
