# Generated by Django 5.1 on 2026-05-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_systemsettings_mqtt_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='mqtt_tls_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
