# Generated by Django 5.1 on 2026-05-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_systemsettings_mqtt_tls_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='mqtt_mode',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='mqtt_tls_enabled',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='mqtt_transport',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='mqtt_broker_host',
            field=models.CharField(default='xxxxxxxx.s1.eu.hivemq.cloud', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='mqtt_broker_port',
            field=models.PositiveIntegerField(default=8883),
        ),
    ]
