# Generated by Django 5.1 on 2026-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_systemsettings_mqtt_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
