# Generated by Django 5.1 on 2026-06-20 13:11

from django.db import migrations, models


def _normalize_session_access_type(apps, schema_editor):
    Session = apps.get_model('dashboard', 'Session')
    Session.objects.filter(access_type__in=['timetable', 'scheduled']).update(access_type='scheduled')
    Session.objects.filter(access_type__in=['none', 'out_of_schedule']).update(access_type='out_of_schedule')
    Session.objects.exclude(access_type__in=['scheduled', 'out_of_schedule']).update(access_type='out_of_schedule')


def _reverse_session_access_type(apps, schema_editor):
    Session = apps.get_model('dashboard', 'Session')
    Session.objects.filter(access_type='scheduled').update(access_type='timetable')
    Session.objects.filter(access_type='out_of_schedule').update(access_type='none')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_classroom_building_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.RunPython(_normalize_session_access_type, _reverse_session_access_type),
        migrations.AlterField(
            model_name='session',
            name='access_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('out_of_schedule', 'Out-of-Schedule')], default='scheduled', max_length=20),
        ),
    ]
