# Generated by Django 5.1 on 2026-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_student_is_active_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(choices=[('INFO', 'Informatique'), ('MATH', 'Mathématiques'), ('ST', 'Sciences et Techniques'), ('SM', 'Sciences de la Matière'), ('MI', 'Mathématiques et Informatique')], max_length=100),
        ),
    ]
