# Generated by Django 5.1 on 2026-06-20 13:42

from django.db import migrations, models


def seed_specializations(apps, schema_editor):
    Student = apps.get_model('dashboard', 'Student')
    Specialization = apps.get_model('dashboard', 'Specialization')

    defaults = [
        ('INFO', 'Informatique'),
        ('MATH', 'Mathematiques'),
        ('ST', 'Sciences et Techniques'),
        ('SM', 'Sciences de la Matiere'),
        ('MI', 'Mathematiques et Informatique'),
    ]

    for code, name in defaults:
        Specialization.objects.get_or_create(code=code, defaults={'name': name, 'is_active': True})

    existing_codes = (
        Student.objects.exclude(specialization__isnull=True)
        .exclude(specialization='')
        .values_list('specialization', flat=True)
        .distinct()
    )

    for code in existing_codes:
        label = str(code).replace('_', ' ').replace('-', ' ').title()
        Specialization.objects.get_or_create(code=code, defaults={'name': label, 'is_active': True})


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_student_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(max_length=30),
        ),
        migrations.RunPython(seed_specializations, noop_reverse),
    ]
