# Generated by Django 5.1 on 2026-06-20 13:46

from django.db import migrations, models


def normalize_student_year_levels(apps, schema_editor):
    Student = apps.get_model('dashboard', 'Student')

    mapping = {
        '1': 'L1',
        'L1': 'L1',
        'LICENCE 1': 'L1',
        'LICENCE1': 'L1',
        '2': 'L2',
        'L2': 'L2',
        'LICENCE 2': 'L2',
        'LICENCE2': 'L2',
        '3': 'L3',
        'L3': 'L3',
        'LICENCE 3': 'L3',
        'LICENCE3': 'L3',
        '4': 'M1',
        'M1': 'M1',
        'MASTER 1': 'M1',
        'MASTER1': 'M1',
        '5': 'M2',
        'M2': 'M2',
        'MASTER 2': 'M2',
        'MASTER2': 'M2',
    }

    for student in Student.objects.all().only('id', 'year'):
        raw = str(student.year or '').strip().upper()
        student.year = mapping.get(raw, 'L1')
        student.save(update_fields=['year'])


def reverse_student_year_levels(apps, schema_editor):
    Student = apps.get_model('dashboard', 'Student')

    reverse_mapping = {
        'L1': '1',
        'L2': '2',
        'L3': '3',
        'M1': '4',
        'M2': '5',
    }

    for student in Student.objects.all().only('id', 'year'):
        student.year = reverse_mapping.get(student.year, '1')
        student.save(update_fields=['year'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_specialization_alter_student_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2),
        ),
        migrations.RunPython(normalize_student_year_levels, reverse_student_year_levels),
    ]
