# Generated by Django 5.1 on 2026-06-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='can_control_lights',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='can_control_projector',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='can_manage_classrooms',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='can_manage_staff',
        ),
    ]
